version: '3.8'

services:
  time-server:
    build: 
      context: ./server
    container_name: time-server
    ports:
      - "123:123/udp"
    healthcheck:
      test: ["CMD-SHELL", "nc -zvu localhost 123 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - clock-net

  client-3h:
    build:
      context: ./client
    container_name: client-3h
    environment:
      - INITIAL_DRIFT_HOURS=3
      - TZ=UTC
    depends_on:
      time-server:
        condition: service_healthy
    networks:
      - clock-net

  client-6h:
    build:
      context: ./client
    container_name: client-6h
    environment:
      - INITIAL_DRIFT_HOURS=6
      - TZ=UTC
    depends_on:
      time-server:
        condition: service_healthy
    networks:
      - clock-net

  client-9h:
    build:
      context: ./client
    container_name: client-9h
    environment:
      - INITIAL_DRIFT_HOURS=9
      - TZ=UTC
    depends_on:
      time-server:
        condition: service_healthy
    networks:
      - clock-net

networks:
  clock-net:
    driver: bridge